digest  =python3 ../ReadTest.py

Ays:	a0 a1 a2 a3 a4 a5 a6 a7 a8 a9

a0:	pf0.sh.o7335039
	${digest}  $^ > $@.dat

a1:	pf1.sh.o7335040
	${digest}  $^ > $@.dat

a2:	pf2.sh.o7335041
	${digest}  $^ > $@.dat

a3:	pf3.sh.o7335042
	${digest}  $^ > $@.dat

a4:	pf4.sh.o7335043
	${digest}  $^ > $@.dat

a5:	pf5.sh.o7335044
	${digest}  $^ > $@.dat

a6:	pf6.sh.o7335045
	${digest}  $^ > $@.dat

a7:	pf7.sh.o7335046
	${digest}  $^ > $@.dat

a8:	pf8.sh.o7335047
	${digest}  $^ > $@.dat

a9:	pf9.sh.o7335048
	${digest}  $^ > $@.dat
